name: Code Quality

on:
  schedule:
  - cron: "* 1 * * *"

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.3'
          elixir-version: '1.11.2'
      - run: mix deps.get
      - run: mix code_quality
