on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['21.3', '22.3']
        elixir: ['1.10.4', '1.11.2']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        with:
          path: deps
          key: dependencies-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix test
  dialyzer:
    runs-on: ubuntu-latest
    name: Dialyzer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.3'
          elixir-version: '1.11.2'
      - uses: actions/cache@v1
        with:
          path: deps
          key: dependencies-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v1
        with:
          path: _build
          key: build-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix dialyzer
  credo:
    runs-on: ubuntu-latest
    name: Credo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.3'
          elixir-version: '1.11.2'
      - uses: actions/cache@v1
        with:
          path: deps
          key: dependencies-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v1
        with:
          path: _build
          key: build-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix credo --strict
