name: Continuous Integration

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['22.3.4', '23.3.4', '24.3.4']
        elixir: ['1.10.4', '1.11.4', '1.12.3']
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: erlef/setup-elixir@v1.16.0
        with:
          version-type: 'strict'
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix deps.get
      - run: mix test
